project:
  type: website

website:
  title: "My Data Analytics Blog"
  navbar:
    center: Chahana Dhakal
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dhakal-chahana
      - icon: twitter
        href: https://twitter.com/dhakal_chahana
      - icon: facebook
        href: https://facebook.com/chahana
       
format:
  html:
    theme: soralis
    css: styles.css
    scheme: dark




editor: visual

